python3 support: fix key-ordering assumption in language test
python dictionaries are not guaranteed to list keys in any particular
order, which was an implicit assumption of following line in
test_language_engine.py

    self.assertEqual(['testA', 'testB'], list(language_engine.code_blocks.keys()))

This invalid assumption was causing test_language_engine.py to fail
in python 3, but I think it could happen in older python as well under
the right circumstances

  ======================================================================
  FAIL: test_050unregister_code_blocks (__main__.TestLanguageEngine)
  Test that code blocks get unregistered properly.
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "./pygame_maker/tests/test_language_engine.py", line 322, in test_050unregister_code_blocks
      self.assertEqual(['testA', 'testB'], list(language_engine.code_blocks.keys()))
  AssertionError: Lists differ: ['testA', 'testB'] != ['testB', 'testA']

  First differing element 0:
  'testA'
  'testB'

  - ['testA', 'testB']
  + ['testB', 'testA']