python3 support: fix language engine exceptions
This was the test_language_engine.py failure, which affected
both python 3 and python 2 (and was the only currently known
regression in python 2):

  ERROR: test_030invalid_syntax (__main__.TestLanguageEngine)
  Test that syntax errors produce the expected exceptions.
  ----------------------------------------------------------------------
  Traceback (most recent call last):

  ...

    File "/home/sjl/repos/pygame_maker/pygame_maker/logic/language_engine.py",
    line 480, in count_function_args

      raise ParseFatalException
  TypeError: __init__() takes at least 2 arguments (1 given)

2to3 took away all arguments when creating exception objects
at the same time as removing the obsolete parentheses for 'raise'

Put back the arguments for exception objects, while leaving the
change from 'raise()' to 'raise'

Also put back __name__ to func_name, because this code is working with
codeblock functions, not trying to access __name__ attribute of builtin
python functions like 2to3 assumed (which used to have an alias
'func_name' in python 2, but got dropped in python 3)

* Original
    raise(ParseFatalException(
        parsestr, loc=loc,
        msg="Too many arguments to function \"{}\"".format(func_name)))

* 2to3 conversion
    raise ParseFatalException

* New
    raise ParseFatalException(
        parsestr, loc=loc,
        msg="Too many arguments to function \"{}\"".format(func_name))