python3 support: comply with stricter object comparison policy
http://portingguide.readthedocs.io/en/latest/comparisons.html
"Python 3 is strict when comparing objects of disparate types. It also
drops cmp-based comparison and sorting in favor of rich comparisons and
key-based sorting, modern alternatives that have been available at least
since Python 2.4. Details and porting strategies follow."

test script failures turned up a couple of places where objects
of different types were being compared and threw errors according
to this new strictness

1. tuple or list vs coordinate.Coordinate

  File "/home/sjl/repos/pygame_maker/pygame_maker/support/coordinate.py",
  line 110, in __eq__
      return (self.x == other.x) and (self.y == other.y)
      AttributeError: 'list' object has no attribute 'x'

2. builtin method vs int

  File "/home/sjl/repos/pygame_maker/pygame_maker/logic/run_time_support.py",
  line 100, in userfunc_randint
    if max < 0:
    TypeError: unorderable types: builtin_function_or_method() < int()

The latter is *definitely* a bug... 'max()' function where 'max_int'
variable should have been